server: 
	gcc server-tcp-example.c -o server-tcp-example; 

run_server:
	./server-tcp-example 9999

client:
	gcc client-tcp-example.c -o client-tcp-example; 

run_client: 
	./client-tcp-example localhost 9999